name: Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  pages: write
  id-token: write

jobs:
  documentation:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
        with:
          submodules: recursive

      - name: Generate Documentation
        run: |
          sudo apt-get install python3 python3-pip
          sudo pip3 install sphinx furo myst-parser sphinx-copybutton linkify-it-py sphinx-togglebutton sphinxemoji
          cd wasplib-docs/docgen/
          python3 docgen.py ../../

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: wasplib-docs/docgen/build/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
