name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2

    - name: Fetch Simba 2 download URL
      id: simba-url
      shell: bash
      run: |
        url="https://raw.githubusercontent.com/Villavu/Simba-Build-Archive/refs/heads/main/latest.win64"
        baseUrl=$(curl -s "$url" | sed 's/Win64\.zip?raw=true$//')
        echo "Base URL: $baseUrl"
        echo "::set-output name=baseUrl::$baseUrl"

    - name: Download Simba 2.0 (64-bit)
      shell: bash
      run: |
        baseUrl="${{ steps.simba-url.outputs.baseUrl }}"
        downloadUrl="${baseUrl}Win64.zip?raw=true"
        echo "Download URL (64-bit): $downloadUrl"
        outputFile="$RUNNER_TEMP/downloaded64.zip"
        curl -o "$outputFile" "$downloadUrl"
        unzip -o "$outputFile" -d ./tests
        rm -f "$outputFile"

    - name: Download Simba 2.0 (32-bit)
      shell: bash
      run: |
        baseUrl="${{ steps.simba-url.outputs.baseUrl }}"
        downloadUrl="${baseUrl}Win32.zip?raw=true"
        echo "Download URL (32-bit): $downloadUrl"
        outputFile="$RUNNER_TEMP/downloaded32.zip"
        curl -o "$outputFile" "$downloadUrl"
        unzip -o "$outputFile" -d ./tests
        rm -f "$outputFile"

    - name: Cache tests folder
      uses: actions/cache@v4
      with:
        path: ./tests
        key: tests-${{ runner.os }}-${{ hashFiles('**/latest.win64') }}
        restore-keys: |
          tests-${{ runner.os }}-

  tests:
    runs-on: windows-latest
    needs: setup

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2

    - name: Restore tests folder from cache
      uses: actions/cache@v4
      with:
        path: ./tests
        key: tests-${{ runner.os }}-${{ hashFiles('**/*.exe') }}
        restore-keys: |
          tests-${{ runner.os }}-

    - name: Run tests
      shell: bash
      run: |
        echo "Contents of the tests folder:"
        ls -R ./tests
